export interface ServiceCenter {
  model_name: string,
  sku: string,
  product_imei_1: string,
  product_imei_2: string,
  product_color: string,
  product_add_time: string,
  product_add_date: string,
  product_price: string,
  product_grade: string,
  vendor_id: number,
  operations_email: string,
  service_stock: number,
  service_center: number,
  is_approved: number,
  storage: string,
  charger: string,
  head_phone: string,
  ejector_tool: string,
  back_cover: string,
  manual: string,
  connector: string,
  remarks: string,
  is_video_taken: number,
  battery_percentage: number,
  is_manual: string,
  count: number
}
