export interface Vendor {
  vendor_id: string,
  first_name: string,
  last_name: string,
  vendor_address:string,
  vendor_pan_number:string,
  vendor_email:string,
  vendor_phone_number:string,
  account_holder_name:string,
  account_number:string,
  bank_name:string,
  branch_name:string,
  gst_number:string,
  ifsc_code:string,
}
